[tool.poetry]
name = "lisp"
version = "0.1.0"
description = ""
authors = ["gala377 <r.galczak@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
